### PR TITLE
osx-arm64 Migrate

### PR DESCRIPTION
**Pull request by mfansler**
Trying to push forward the migration stalled out in PR #22.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mfansler** [comment]
@conda-forge-admin, please rerender

**Comment by mfansler** [comment]
@colinbrislawn do have any thoughts on this? I had seen your previous solutions for stalled out migrations and am trying to recapitulate.

**Comment by colinbrislawn** [comment]
We are back to this error:

>Invalid configuration `arm64-apple-darwin20.0.0': machine `arm64-apple' not recognized

There's this workaround from [this post](https://github.com/libffi/libffi/issues/152#issuecomment-174260864)
`echo 'echo arm-apple-darwin' > config.sub`
but I think updating the feedstock and autogenerating new code would also solve the problem. I'm not sure how's the best way to do this...

**Comment by mfansler** [comment]
@colinbrislawn thanks for looking 🙏. I thought that failed in the previous attempt (#20). My impression was copying from `gnuconfig` was a better approach. Also, the migration bot rerendered recently (#22), and this PR starts from that.

**Comment by colinbrislawn** [comment]
Thanks for telling me more!

You may have a better idea of how to do this than I do. I starting building these because I needed them, but I don't have a background in cross compiling software.

**Comment by mfansler** [comment]
Okay, think I tracked the failure down to the fact that this package is (and probably shouldn't be!) redistributing `nlopt`, under the `src/nlopt_src` directory and this has its own outdated `config.sub` file lacking `arm64-apple-darwin*` matching.

The pakcage's compilation strategy appears to detect the presence of system-level `nlopt` for *nix builds. Hoping adding that as a dependency might mitigate the issue.

**Comment by mfansler** [comment]
Hmm. Actually seems like this pulls in Python - something I do not think we should do. Instead, I'm going to keep dependency out, and instead try precisely replacing the `src/nlopt_src/config.sub`.

I dropped an issue on the `nlopt-feedstock` to explore splitting that recipe to build separate C++ library and Python bindings. See conda-forge/nlopt-feedstock#41.

**Comment by mfansler** [comment]
Still unresolved issues with compiling the redistributed library. For now, using `nlopt-feedstock` might be the most efficacious, despite it pulling in Python. That's an issue for that feedstock to fix.

**Comment by mfansler** [comment]
@colinbrislawn I'm adding you as maintainer in this PR - okay?

closes #18 #19 #20 #22

**Comment by mfansler** [comment]
@rvalieris @conda-forge/help-r this is ready for review.

Summarily, this switches all platforms to use the `nlopt` package (previously only **win-\***), rather than redistributing, which is where the **osx-arm64** builds failed. It should be noted that this results in pulling in `python` in solves, but that is something I believe should be fixed in the `nlopt-feedstock`, not here (see conda-forge/nlopt-feedstock#41).

**Comment by mfansler** [comment]
@conda-forge/r ready for review 🙏 (see summary in previous comment).

**Comment by mfansler** [comment]
@conda-forge/core please review (new maintainer)

**Pull request merged**
